services:
  - type: web
    name: e-commerce-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        sync: false
      - key: ADMIN_FRONTEND_URL
        sync: false
      - key: CORS_ORIGINS
        sync: false
      - key: MONGODB_URL
        sync: false
      - key: CLOUDINARY_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
